#	           _     _                                      _
#	  __ _  __| | __| |     _ __  _ __ ___  _ __   ___ _ __| |_ _   _
#	 / _` |/ _` |/ _` |    | '_ \| '__/ _ \| '_ \ / _ \ '__| __| | | |
#	| (_| | (_| | (_| |    | |_) | | | (_) | |_) |  __/ |  | |_| |_| |
#	 \__,_|\__,_|\__,_|____| .__/|_|  \___/| .__/ \___|_|   \__|\__, |
#	                 |_____|_|             |_|                  |___/
#
#	This is an update example for the ADD_PROPERTY update

prefix wot: <http://wot.arces.unibo.it/ontology/web_of_things#>
prefix dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

delete {
  <http://MySecondWebThing.com/Property2> wot:hasName ?oldName;
            wot:hasStability ?oldStability;
            wot:isWritable ?oldWritability;
            wot:hasDataSchema ?oldDS;
            wot:hasPropertyDataSchema ?oldPDS;
            wot:hasPropertyData ?oldPData.
  ?oldPData rdf:type wot:PropertyData, dul:InformationObject;
            dul:hasDataValue ?oldValue }
insert {
  <http://MySecondWebThing.com/Property2> rdf:type wot:Property, wot:InteractionPattern;
            wot:hasName 'new_property_name';
            wot:hasStability '314';
            wot:isWritable 'false';
            wot:hasDataSchema <http://MySecondWebThing.com/Property2/DataSchema/property>;
            wot:hasPropertyDataSchema <http://MySecondWebThing.com/Property2/DataSchema/property>;
            wot:hasPropertyData <http://MySecondWebThing.com/Property2/PropertyData>.
  <http://MySecondWebThing.com/Property2/PropertyData> rdf:type wot:PropertyData, dul:InformationObject;
            dul:hasDataValue 'Another one bites the dust' }
where {
  optional {
    <http://MySecondWebThing.com/Property2> wot:hasName ?oldName;
            wot:hasStability ?oldStability;
            wot:isWritable ?oldWritability;
            wot:hasDataSchema ?oldDS;
            wot:hasPropertyDataSchema ?oldPDS;
            wot:hasPropertyData ?oldPData.
  ?oldPData rdf:type wot:PropertyData, dul:InformationObject;
            dul:hasDataValue ?oldValue }
  }