#	           _     _     ___ ___               _   _
#	  __ _  __| | __| |   |_ _/ _ \    __ _  ___| |_(_) ___  _ __
#	 / _` |/ _` |/ _` |    | | | | |  / _` |/ __| __| |/ _ \| '_ \
#	| (_| | (_| | (_| |    | | |_| | | (_| | (__| |_| | (_) | | | |
#	 \__,_|\__,_|\__,_|___|___\___/___\__,_|\___|\__|_|\___/|_| |_|
#	                 |_____|     |_____|
#	
#	This is an update example for the ADD_IO_ACTION update, i.e. an Action with both output and input

delete {
  <http://MyFirstWebThing.com/Action1> wot:hasName ?oldName;
          wot:hasDataSchema ?oldDSs;
          wot:hasInputDataSchema ?oldIDS;
          wot:hasOutputDataSchema ?oldODS. }
insert {
  <http://MyFirstWebThing.com/Action1> rdf:type wot:InteractionPattern, wot:Action;
          wot:hasName 'my_new_name';
          wot:hasDataSchema <http://MyFirstWebThing.com/Action1/DataSchema/input2>, <http://MyFirstWebThing.com/Action1/DataSchema/output2>;
          wot:hasInputDataSchema <http://MyFirstWebThing.com/Action1/DataSchema/input2>;
          wot:hasOutputDataSchema <http://MyFirstWebThing.com/Action1/DataSchema/output2>. }
where {
  optional {
    <http://MyFirstWebThing.com/Action1> wot:hasName ?oldName;
          wot:hasDataSchema ?oldDSs;
          wot:hasInputDataSchema ?oldIDS;
          wot:hasOutputDataSchema ?oldODS. }
  }