#	           _     _               _     _   _     _
#	  __ _  __| | __| |    ___ _   _| |__ | |_| |__ (_)_ __   __ _
#	 / _` |/ _` |/ _` |   / __| | | | '_ \| __| '_ \| | '_ \ / _` |
#	| (_| | (_| | (_| |   \__ \ |_| | |_) | |_| | | | | | | | (_| |
#	 \__,_|\__,_|\__,_|___|___/\__,_|_.__/ \__|_| |_|_|_| |_|\__, |
#	                 |_____|                                 |___/
#
#	This is an example of add_subthing SPARQL.

prefix wot: <http://wot.arces.unibo.it/ontology/web_of_things#>
prefix dul: <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

insert {
	<http://MyFirstWebThing.com> wot:hasSubThing <http://MyThirdWebThing.com> }
where {
	<http://MyFirstWebThing.com> rdf:type wot:Thing.
	<http://MyThirdWebThing.com> rdf:type wot:Thing.
}
