#                           _               _   _                 _           _   
#     _ __   _____      __ (_)    __ _  ___| |_(_) ___  _ __     (_)_ __  ___| |_ 
#    | '_ \ / _ \ \ /\ / / | |   / _` |/ __| __| |/ _ \| '_ \    | | '_ \/ __| __|
#    | | | |  __/\ V  V /  | |  | (_| | (__| |_| | (_) | | | |   | | | | \__ \ |_ 
#    |_| |_|\___| \_/\_/___|_|___\__,_|\___|\__|_|\___/|_| |_|___|_|_| |_|___/\__|
#                     |_____|_____|                         |_____|               
#                          
#      __ _ _ __   ___ ___ 
#     / _` | '_ \ / __/ _ \
#    | (_| | | | | (_|  __/
#     \__,_|_| |_|\___\___|
#                          
#    

NEW_I_ACTION_INSTANCE:
    sparql: "
        delete {
            ?action wot:hasActionInstance ?oldAInstance.
            ?oldAInstance   rdf:type wot:ActionInstance;
							wot:hasRequestTimeStamp ?oldATS;
                            wot:hasConfirmationTimeStamp ?oldCTS;
                            wot:hasCompletionTimeStamp ?oldCCTS;
                            wot:requestedBy ?oldAuthor;
                            wot:hasInputData ?oldIData.
            ?oldIData   dul:hasDataValue ?oldIValue;
                        wot:hasInputDataSchema ?oldIDS}
        insert {
            ?action wot:hasActionInstance ?newAInstance.
            ?newAInstance   rdf:type wot:ActionInstance;
							wot:hasRequestTimeStamp ?newATS;
                            wot:requestedBy ?newAuthor;
                            wot:hasInputData ?newIData.
            ?newIData   dul:hasDataValue ?newIValue;
                        wot:hasInputDataSchema ?newIDS}
        where {
            ?action rdf:type wot:Action.
            optional {
                ?action wot:hasActionInstance ?oldAInstance.
                ?oldAInstance   rdf:type wot:ActionInstance;
								wot:hasRequestTimeStamp ?oldATS;
                                wot:hasConfirmationTimeStamp ?oldCTS;
                                wot:hasCompletionTimeStamp ?oldCCTS;
                                wot:requestedBy ?oldAuthor;
                                wot:hasInputData ?oldIData.
                ?oldIData   dul:hasDataValue ?oldIValue;
                            wot:hasInputDataSchema ?oldIDS
            }
            bind (now() as ?newATS)
        }
        "
    forcedBindings:
        action:
            type: uri
            value: ""
        newAInstance:
            type: uri
            value: ""
        newAuthor:
            type: uri
            value: ""
        newIData:
            type: uri
            value: ""
        newIValue:
            type: literal
            value: ""
        newIDS:
            type: uri
            value: ""
